server:
  port: 8081
  ssl:
    enabled: true
    key-store: file:/app/zaoraj-be.p12
    key-store-password: ${admin.keystore.password}
    key-store-type: PKCS12
    key-alias: zaoraj
spring:
  ai:
    openai:
      api-key: ${admin.openai.key}